"use strict";
exports.__esModule = true;
var express_1 = require("express");
var cors_1 = require("cors");
var app = (0, express_1["default"])();
var base_1 = require("./controllers/base");
app.use((0, cors_1["default"])());
app.use(express_1["default"].static("build"));
app.use(express_1["default"].json());
app.use("/api/ping", base_1["default"]);
exports["default"] = app;
